---

- hosts: all
  gather_facts: False
  connection: local
  vars:
    targetips: "{{ targetipsinput | default('') }}"

  tasks:
    
    - name: Convert comma-separated string to list
      set_fact:
        targetiplist: "{{ targetipsinput.split(',') }}"    
        
    
    - name: Display IP addresses
      debug:
        msg: "Pinging each IP address: {{ item }}"
      with_items: "{{ targetiplist }}"

    - name: ping
      shell: ping -c 1 -w 2 {{ item }}
      with_items: "{{ targetips }}"
      ignore_errors: true
