---

- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Display IP address
      debug:
        msg: "Pinging IP address: {{ target_ip }}"
     
    - name: ping
      shell: ping -c 1 -w 2 {{ target_ip }}
      
      
    
