---
- name: Ping Target Host
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: target_ip
      prompt: "Enter the IP address to ping"
      private: no

  tasks:
    - name: Ping the specified IP
      ping:
      args:
        data: "{{ target_ip }}"
